version: '3.8'

services:
  postgres-user:
    image: postgres:15
    container_name: postgres_user_container
    restart: always
    environment:
      POSTGRES_USER: user_user
      POSTGRES_PASSWORD: user_password
      POSTGRES_DB: user_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_user_data:/var/lib/postgresql/data
    networks:
      - app-network

  postgres-movie:
    image: postgres:15
    container_name: postgres_movie_container
    restart: always
    environment:
      POSTGRES_USER: movie_user
      POSTGRES_PASSWORD: movie_password
      POSTGRES_DB: movie_db
    ports:
      - "5434:5432"
    volumes:
      - postgres_movie_data:/var/lib/postgresql/data
    networks:
      - app-network

  postgres-booking:
    image: postgres:15
    container_name: postgres_booking_container
    restart: always
    environment:
      POSTGRES_USER: booking_user
      POSTGRES_PASSWORD: booking_password
      POSTGRES_DB: booking_db
    ports:
      - "5435:5432"
    volumes:
      - postgres_booking_data:/var/lib/postgresql/data
    networks:
      - app-network

  eureka-server:
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    container_name: eureka-server
    ports:
      - '8761:8761'
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/eureka"]
      interval: 30s
      timeout: 10s
      retries: 3

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - '8080:8080'
    environment:
      - 'EUREKA_SERVER_URL=http://eureka-server:8761/eureka'
    depends_on:
      - eureka-server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_user_data:
  postgres_movie_data:
  postgres_booking_data: