version: '3.8'

services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'

  eureka-server:
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    container_name: eureka-server
    ports:
      - '8761:8761'
    networks:
      - app-network

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - '8080:8080'
    environment:
      - 'EUREKA_SERVER_URL=http://eureka-server:8761/eureka'
    depends_on:
      - eureka-server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge