server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
        - id: movie-service
          uri: lb://movie-service
          predicates:
            - Path=/movies/**
        - id: booking-service
          uri: lb://booking-service
          predicates:
            - Path=/bookings/**

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
  instance:
    preferIpAddress: true
