server:
  port: 8082

spring:
  application:
    name: movie-service
  datasource:
    url: jdbc:postgresql://postgres-movie:5432/movie_db
    username: movie_user
    password: movie_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka

springdoc:
  swagger-ui:
    path: /swagger-ui.html